"""add document table

Revision ID: 14f31d868bd7
Revises: 184ea83058a6
Create Date: 2026-04-20 16:36:40.113209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14f31d868bd7'
down_revision: Union[str, Sequence[str], None] = '184ea83058a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False, comment='文档ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment="原始文件名,如'报告.pdf'"),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment="对象存储路径,如'/uploads/2026/04/xxx.pdf'"),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_extension', sa.String(length=20), nullable=False, comment="文件后缀,如'pdf','docx','txt'"),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment="MIME类型,如'application/pdf'"),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_documents_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('session_documents',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_session_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_session_documents_session_id_chat_session')),
    sa.PrimaryKeyConstraint('session_id', 'document_id', name=op.f('pk_session_documents'))
    )
    # 先删除中间表，再删除被引用的表
    op.drop_table('article_tag')
    op.drop_table('article')
    op.drop_table('tag')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.create_table('article_tag',
    sa.Column('article_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_article_tag_article_id_article')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_article_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_article_author_id_user')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('session_documents')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
